// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VastgoedAPI.Data;

#nullable disable

namespace VastgoedAPI.Migrations
{
    [DbContext(typeof(VastgoedDbContext))]
    partial class VastgoedDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("HuurderId")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VerhuurderID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HuurderId");

                    b.HasIndex("VerhuurderID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PasswordHash = "$2a$11$3TOPat0sFuCoE98r8.ZY9.E1juFqzQG3sV9wRnvoNRRmUTkxlTWMe",
                            Role = "admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            PasswordHash = "$2a$11$yKM.VbOQzYMh6aPN7fsOA.YHAYpkNH2NXe/Zt4ZnU4SRPssZjj.Mm",
                            Role = "user",
                            Username = "user"
                        },
                        new
                        {
                            Id = 3,
                            PasswordHash = "$2a$11$lhjeqzOHDaA1YTSMvEtTj.hNJIAb9v9bnrhtFsobI6NQC8zRTUZIe",
                            Role = "manager",
                            Username = "manager"
                        },
                        new
                        {
                            Id = 4,
                            PasswordHash = "$2a$11$F6G1qDmXxt5FTzTQjY8gfezph5euDMKfBe0jdL4BcXPHTOohOLrEm",
                            Role = "owner",
                            Username = "owner"
                        },
                        new
                        {
                            Id = 5,
                            PasswordHash = "$2a$11$oen.5Rdyvqw/XtAb4Ki2iuRZIn6K41AjJWsYb8oS64zlm9pDyfc1a",
                            Role = "guest",
                            Username = "guest"
                        });
                });

            modelBuilder.Entity("VastgoedAPI.Models.Contract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EindDatum")
                        .HasColumnType("datetime2");

                    b.Property<int>("HuurderID")
                        .HasColumnType("int");

                    b.Property<decimal>("Huurprijs")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StartDatum")
                        .HasColumnType("datetime2");

                    b.Property<int>("VastgoedID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HuurderID");

                    b.HasIndex("VastgoedID");

                    b.ToTable("Contracten");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EindDatum = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HuurderID = 1,
                            Huurprijs = 850m,
                            StartDatum = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VastgoedID = 1
                        },
                        new
                        {
                            Id = 2,
                            EindDatum = new DateTime(2026, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HuurderID = 2,
                            Huurprijs = 450m,
                            StartDatum = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VastgoedID = 2
                        },
                        new
                        {
                            Id = 3,
                            EindDatum = new DateTime(2024, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HuurderID = 3,
                            Huurprijs = 1200m,
                            StartDatum = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VastgoedID = 3
                        },
                        new
                        {
                            Id = 4,
                            EindDatum = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HuurderID = 4,
                            Huurprijs = 950m,
                            StartDatum = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VastgoedID = 4
                        },
                        new
                        {
                            Id = 5,
                            EindDatum = new DateTime(2024, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HuurderID = 5,
                            Huurprijs = 600m,
                            StartDatum = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VastgoedID = 5
                        });
                });

            modelBuilder.Entity("VastgoedAPI.Models.Huurder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefoon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Huurders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "jan@example.com",
                            Naam = "Jan Janssens",
                            Telefoon = "0470123456"
                        },
                        new
                        {
                            Id = 2,
                            Email = "anke@coremans.be",
                            Naam = "Anke Coremans",
                            Telefoon = "0471234567"
                        },
                        new
                        {
                            Id = 3,
                            Email = "pieter@peeters.be",
                            Naam = "Pieter Peeters",
                            Telefoon = "0472345678"
                        },
                        new
                        {
                            Id = 4,
                            Email = "sofie@smets.be",
                            Naam = "Sofie Smets",
                            Telefoon = "0473456789"
                        },
                        new
                        {
                            Id = 5,
                            Email = "tom@timmers.be",
                            Naam = "Tom Timmers",
                            Telefoon = "0474567890"
                        });
                });

            modelBuilder.Entity("VastgoedAPI.Models.Transactie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Bedrag")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Categorie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<string>("Omschrijving")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("VastgoedId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VastgoedId");

                    b.ToTable("Transacties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bedrag = 850m,
                            Categorie = "Huur",
                            Datum = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Omschrijving = "Huurbetaling januari",
                            Type = 0,
                            VastgoedId = 1
                        },
                        new
                        {
                            Id = 2,
                            Bedrag = 850m,
                            Categorie = "Huur",
                            Datum = new DateTime(2025, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Omschrijving = "Huurbetaling februari",
                            Type = 0,
                            VastgoedId = 1
                        },
                        new
                        {
                            Id = 3,
                            Bedrag = -200m,
                            Categorie = "Onderhoud",
                            Datum = new DateTime(2025, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Omschrijving = "Onderhoud verwarmingsketel",
                            Type = 1,
                            VastgoedId = 1
                        },
                        new
                        {
                            Id = 4,
                            Bedrag = 450m,
                            Categorie = "Huur",
                            Datum = new DateTime(2025, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Omschrijving = "Huurbetaling september",
                            Type = 0,
                            VastgoedId = 2
                        },
                        new
                        {
                            Id = 5,
                            Bedrag = 450m,
                            Categorie = "Huur",
                            Datum = new DateTime(2025, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Omschrijving = "Huurbetaling oktober",
                            Type = 0,
                            VastgoedId = 2
                        },
                        new
                        {
                            Id = 6,
                            Bedrag = -150m,
                            Categorie = "Reparatie",
                            Datum = new DateTime(2025, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Omschrijving = "Reparatie lekkage badkamer",
                            Type = 1,
                            VastgoedId = 2
                        },
                        new
                        {
                            Id = 7,
                            Bedrag = 450m,
                            Categorie = "Huur",
                            Datum = new DateTime(2025, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Omschrijving = "Huurbetaling december",
                            Type = 0,
                            VastgoedId = 2
                        },
                        new
                        {
                            Id = 8,
                            Bedrag = -50m,
                            Categorie = "Schoonmaak",
                            Datum = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Omschrijving = "Schoonmaakkosten",
                            Type = 1,
                            VastgoedId = 2
                        },
                        new
                        {
                            Id = 9,
                            Bedrag = 1200m,
                            Categorie = "Huur",
                            Datum = new DateTime(2025, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Omschrijving = "Huurbetaling mei",
                            Type = 0,
                            VastgoedId = 3
                        },
                        new
                        {
                            Id = 10,
                            Bedrag = 1200m,
                            Categorie = "Huur",
                            Datum = new DateTime(2025, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Omschrijving = "Huurbetaling juni",
                            Type = 0,
                            VastgoedId = 3
                        },
                        new
                        {
                            Id = 11,
                            Bedrag = 1200m,
                            Categorie = "Huur",
                            Datum = new DateTime(2025, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Omschrijving = "Huurbetaling juli",
                            Type = 0,
                            VastgoedId = 3
                        },
                        new
                        {
                            Id = 12,
                            Bedrag = -300m,
                            Categorie = "Onderhoud",
                            Datum = new DateTime(2025, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Omschrijving = "Tuinonderhoud",
                            Type = 1,
                            VastgoedId = 3
                        },
                        new
                        {
                            Id = 13,
                            Bedrag = 950m,
                            Categorie = "Huur",
                            Datum = new DateTime(2025, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Omschrijving = "Huurbetaling maart",
                            Type = 0,
                            VastgoedId = 4
                        },
                        new
                        {
                            Id = 14,
                            Bedrag = 950m,
                            Categorie = "Huur",
                            Datum = new DateTime(2025, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Omschrijving = "Huurbetaling april",
                            Type = 0,
                            VastgoedId = 4
                        },
                        new
                        {
                            Id = 15,
                            Bedrag = -100m,
                            Categorie = "Renovatie",
                            Datum = new DateTime(2025, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Omschrijving = "Schilderwerk woonkamer",
                            Type = 1,
                            VastgoedId = 4
                        },
                        new
                        {
                            Id = 16,
                            Bedrag = 600m,
                            Categorie = "Huur",
                            Datum = new DateTime(2025, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Omschrijving = "Huurbetaling juli",
                            Type = 0,
                            VastgoedId = 5
                        },
                        new
                        {
                            Id = 17,
                            Bedrag = 600m,
                            Categorie = "Huur",
                            Datum = new DateTime(2025, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Omschrijving = "Huurbetaling augustus",
                            Type = 0,
                            VastgoedId = 5
                        },
                        new
                        {
                            Id = 18,
                            Bedrag = -75m,
                            Categorie = "Reparatie",
                            Datum = new DateTime(2025, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Omschrijving = "Vervanging slot voordeur",
                            Type = 1,
                            VastgoedId = 5
                        });
                });

            modelBuilder.Entity("VastgoedAPI.Models.Vastgoed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Kamers")
                        .HasColumnType("int");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Oppervlakte")
                        .HasColumnType("float");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VerhuurderID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VerhuurderID");

                    b.ToTable("Vastgoed");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Adres = "Lebonstraat 10, 2240 Geel",
                            Kamers = 2,
                            Naam = "Appartement Geel",
                            Oppervlakte = 75.0,
                            Type = "Appartement",
                            VerhuurderID = 1
                        },
                        new
                        {
                            Id = 2,
                            Adres = "Italiëlei 11, 2000 Antwerpen",
                            Kamers = 1,
                            Naam = "Studentenkot Campus Italia",
                            Oppervlakte = 30.0,
                            Type = "Studentenkot",
                            VerhuurderID = 2
                        },
                        new
                        {
                            Id = 3,
                            Adres = "Dorpstraat 5, 2240 Zandhoven",
                            Kamers = 4,
                            Naam = "Villa Zandhoven",
                            Oppervlakte = 200.0,
                            Type = "Villa",
                            VerhuurderID = 3
                        },
                        new
                        {
                            Id = 4,
                            Adres = "Kloosterstraat 20, 2000 Antwerpen",
                            Kamers = 3,
                            Naam = "Loft Antwerpen",
                            Oppervlakte = 120.0,
                            Type = "Loft",
                            VerhuurderID = 4
                        },
                        new
                        {
                            Id = 5,
                            Adres = "Naamsestraat 100, 3000 Leuven",
                            Kamers = 1,
                            Naam = "Studio Leuven",
                            Oppervlakte = 40.0,
                            Type = "Studio",
                            VerhuurderID = 5
                        });
                });

            modelBuilder.Entity("VastgoedAPI.Models.Verhuurder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefoon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Verhuurders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "info@vastgoedbv.be",
                            Naam = "Vastgoed BV",
                            Telefoon = "0212345678"
                        },
                        new
                        {
                            Id = 2,
                            Email = "contact@immogroup.be",
                            Naam = "Immo Group",
                            Telefoon = "0223456789"
                        },
                        new
                        {
                            Id = 3,
                            Email = "partners@realestate.be",
                            Naam = "Real Estate Partners",
                            Telefoon = "0234567890"
                        },
                        new
                        {
                            Id = 4,
                            Email = "info@urbanliving.be",
                            Naam = "Urban Living",
                            Telefoon = "0245678901"
                        },
                        new
                        {
                            Id = 5,
                            Email = "contact@cityrentals.be",
                            Naam = "City Rentals",
                            Telefoon = "0256789012"
                        });
                });

            modelBuilder.Entity("User", b =>
                {
                    b.HasOne("VastgoedAPI.Models.Huurder", "Huurder")
                        .WithMany()
                        .HasForeignKey("HuurderId");

                    b.HasOne("VastgoedAPI.Models.Verhuurder", "Verhuurder")
                        .WithMany()
                        .HasForeignKey("VerhuurderID");

                    b.Navigation("Huurder");

                    b.Navigation("Verhuurder");
                });

            modelBuilder.Entity("VastgoedAPI.Models.Contract", b =>
                {
                    b.HasOne("VastgoedAPI.Models.Huurder", "Huurder")
                        .WithMany("Contracten")
                        .HasForeignKey("HuurderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VastgoedAPI.Models.Vastgoed", "Vastgoed")
                        .WithMany("Contracten")
                        .HasForeignKey("VastgoedID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Huurder");

                    b.Navigation("Vastgoed");
                });

            modelBuilder.Entity("VastgoedAPI.Models.Transactie", b =>
                {
                    b.HasOne("VastgoedAPI.Models.Vastgoed", "Vastgoed")
                        .WithMany("Transacties")
                        .HasForeignKey("VastgoedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vastgoed");
                });

            modelBuilder.Entity("VastgoedAPI.Models.Vastgoed", b =>
                {
                    b.HasOne("VastgoedAPI.Models.Verhuurder", "Verhuurder")
                        .WithMany("Vastgoed")
                        .HasForeignKey("VerhuurderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Verhuurder");
                });

            modelBuilder.Entity("VastgoedAPI.Models.Huurder", b =>
                {
                    b.Navigation("Contracten");
                });

            modelBuilder.Entity("VastgoedAPI.Models.Vastgoed", b =>
                {
                    b.Navigation("Contracten");

                    b.Navigation("Transacties");
                });

            modelBuilder.Entity("VastgoedAPI.Models.Verhuurder", b =>
                {
                    b.Navigation("Vastgoed");
                });
#pragma warning restore 612, 618
        }
    }
}
